$targetFile = Join-Path (Split-Path -parent $PSCommandPath) "..\build\assets.props";

$platforms = @(
    @{
        Platform = "x64";
        VCPlatform = "x64";
    },
    @{
        Platform = "x86";
        VCPlatform = "Win32";
    }
);
$srcDir = "`$(MSBuildThisFileDirectory)..\src";
$projects = @(
    @{
        ProjectDirectory = "$srcDir\AspNetCoreModuleV1\AspNetCore";
        ProjectName = "AspNetCore.vcxproj";
        NativeAsset = "aspnetcore";
        BaseOutputPath = "AspNetCoreModuleV1"
     },
     @{
        ProjectDirectory = "$srcDir\AspNetCoreModuleV2\AspNetCore";
        ProjectName = "`AspNetCore.vcxproj";
        NativeAsset = "aspnetcorev2";
        BaseOutputPath = "AspNetCoreModuleV2"
     },
     @{
        ProjectDirectory = "$srcDir\AspNetCoreModuleV2\InProcessRequestHandler";
        ProjectName = "InProcessRequestHandler.vcxproj";
        NativeAsset = "aspnetcorev2_inprocess";
        BaseOutputPath = "AspNetCoreModuleV2";
     },
     @{
        ProjectDirectory = "$srcDir\AspNetCoreModuleV2\OutOfProcessRequestHandler";
        ProjectName = "OutOfProcessRequestHandler.vcxproj";
        NativeAsset = "aspnetcorev2_outofprocess";
        BaseOutputPath = "AspNetCoreModuleV2";
        PackageSubPath = "`$(AspNetCoreModuleOutOfProcessVersion)\";
     }
);
$components = @();
$shimComponents = @();
$inProcessComponents = @();

function CopyProperties($from, $to)
{
    foreach ($key in $from.Keys)
    {
        $to.Add($key, $from.$key);
    }
}

function Write-Group($group, $name)
{
    return $(
        foreach ($item in $group){
        "       <$name$(foreach ($pair in $item.GetEnumerator()) {
        "`n          $($pair.Key)=`"`"$($pair.Value)`"`""})
        />`n"});
}

foreach ($project in $projects)
{
    foreach ($platform in $platforms)
    {
        $component = [ordered]@{};
        CopyProperties -from $platform -to $component;
        CopyProperties -from $project -to $component;
        CopyProperties -from @{
            Include = "$($project.ProjectDirectory)\$($project.ProjectName)";
            DllLocation = "$($project.ProjectDirectory)\bin\`$(Configuration)\$($platform.VCPlatform)\$($project.NativeAsset).dll";
            PdbLocation = "$($project.ProjectDirectory)\bin\`$(Configuration)\$($platform.VCPlatform)\$($project.NativeAsset).pdb";
        } -to $component;
        $components += $component;

        if ($project.ProjectName.Contains("InProcess"))
        {
            $inProcessComponents += $component;
        }
        else
        {
            $shimComponents += $component;
        }
    }
}

@"
<!-- This file is autogenerated -->
<Project>
    <ItemGroup>
$(Write-Group $components "Components" )
$(Write-Group $shimComponents "ShimComponents")
$(Write-Group $inProcessComponents "InProcessComponents")
    </ItemGroup>
</Project>
"@ > $targetFile
